pipeline {
    agent any
 tools {
        maven 'local_maven'
    }

    stages {
        
        stage('api-gateway') {
            steps {
                 dir('api-gateway') {
                    sh 'mvn clean package -Dmaven.test.skip=true'

                }
            }
                
        }

        
        }
    }
